Vagrant.configure("2") do |config|
  config.vm.box = "rocky-ynov"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = "1024"
  end

  config.vm.box_check_update = false 

  config.vm.synced_folder ".", "/vagrant", disabled: true
  
  config.vm.define "vm1" do |vm1|
    vm1.vm.network "private_network", type: "dhcp"
    vm1.vm.network "private_network", ip: "10.1.1.11"
    vm1.vm.hostname = "vm1.tp0"
  end

  config.vm.define "vm2" do |vm2|
    vm2.vm.network "private_network", type: "dhcp"
    vm2.vm.network "private_network", ip: "10.1.1.12"
    vm2.vm.hostname = "vm2.tp0"
  end

  config.vm.provision "shell", path: "setup.sh"
end
